# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8564706df755f28ff79238c150379c4045cb079353fed13aea584ea4161f4c686bd545658f47e78990b8186c6b9de0fac55cf2fd554b29ed67ff1768fa8c0add

test:
  secret_key_base: 8b2ed684491706419f3abf07520bfe0e9b44ece16877ad053b36a8cb53f06af9b6a9bd2a85d97c947d5ff0d81492bf5c6a71c1a7abee528ea1ad376db1261266

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
